pipeline {
    agent {
        label 'AGENT-1'
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        //retry(1)
    }
     // Parameters passed to CD
     // These come either:
    // 1. From CI trigger OR
    // 2. Manual "Build with Parameters"
    parameters{
        choice(name: 'ENVIRONMENT', choices: ['dev', 'qa', 'uat', 'pre-prod', 'prod'], description: 'Select your Environment')
        string(name: 'version',  description: 'Enter your application version')
        string(name: 'jira-id',  description: 'Enter your jira id')
    }
    environment {
        appVersion = '' // this will become global, we can use across pipeline
        region = 'us-east-1'
        account_id = ''
        project = 'roboshop'
        env_name = ''
        component = 'cart'
    }

    stages {
        stage('Setup Environment'){
           steps {
                script {
                    /*
                    Assign Jenkins parameters to environment variables.
                    This makes them globally available in later stages.
                     */
                    env.env_name = params.ENVIRONMENT //example if i choose dev now the env_name = dev
                    env.appVersion = params.version

                    echo "Selected environment: ${env.env_name}"
                    echo "App version: ${env.appVersion}"

                    account_id = pipelineGlobals.getAccountID(env.env_name)

                    echo "Environment  : ${env.env_name}"
                    echo "App Version  : ${env.appVersion}"
                    echo "Account ID  : ${account_id}"
                }
            }
        }
        stage('Integration tests'){
            when {
                expression {params.ENVIRONMENT == 'qa'}
            }
            steps{
                script{
                    sh """
                        echo "Run integration tests"
                    """
                }
            }
        }
        stage('Check JIRA'){
            when {
                expression {params.ENVIRONMENT == 'prod'}
            }
            steps{
                script{
                    sh """
                        echo "check jira status"
                        echo "check jira deployment window"
                        echo "fail pipeline if above two are not true"
                    """
                }
            }
        }
        stage('Deploy'){
            steps {
                // Authenticate with AWS using Jenkins credentials
                withAWS(region: 'us-east-1', credentials: "aws-creds-${env.env_name}"){
                // Move into Helm chart directory
                    dir('cart-deploy/helm') {
                        sh """
                            # Update kubeconfig for the target EKS cluster
                            # Example: expense-dev, expense-qa, expense-prod
                            aws eks update-kubeconfig --region ${region} --name ${project}-${env.env_name}

                            # Replace IMAGE_VERSION in helm values file with the exact app version
                            # values-dev.yaml / values-qa.yaml / etc
                            sed -i "s/IMAGE_VERSION/${env.appVersion}/g" values-${env.env_name}.yaml

                            # Verify replacement
                            cat values-${env.env_name}.yaml

                            # Deploy or upgrade application using Helm
                            helm upgrade --install ${component} -n ${project} -f values-${env.env_name}.yaml .
                        """
                    }
                }
            }
        }
    }

    post {
        always{
            echo "This sections runs always"
            deleteDir()
        }
        success{
            echo "This section run when pipeline success"
        }
        failure{
            echo "This section run when pipeline failure"
        }
    }
}